### ISSUE TITLE
상속 관련 질문입니다.

### ISSUE THREAD

**Issue by LimHyungang** [seed-kau/JavaStudy#13]
github 사용이 미숙하여 질문라벨을 달지 못하였습니다.
양해 부탁드립니다

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

큳래스 A, B가 있습니다.

B는 A를 상속받습니다

public class B extends A 

또한 Object클래스는 모든 클래스의 부모 클래스이므로 A는 Object의 자식일 것입니다.

고로 아래와 같은 가계도(?)가 예상이 됩니다.
Object <-- A <-- B  

이는 다중상속을 지원하지 않는다는 자바의 속성에 위배되는 것으로 보이지만 제가 이해를 못 하는 것일 뿐 잘못된 점이 있는 건 아니겠죠

이에 대해서 아래와 같은 생각을 해보았습니다.

1. Object클래스를 포함한 다중상속은 예외적으로 허용될 수 있다?

or

2. 자바에서 금지하는 '다중상속'이라 함은  
class C extends B extensd A 
이런 형태를 말하고

class C extends B
class B extends A 
이런 형태의 상속은 '다중상속'으로 취급하지 않는다?

1,2중 정답이 있는지 궁금합니다. 아니라면 적절한 조언을 부탁드립니다.

감사합니다.

**Comment by Danpatpang** [comment]
어떻게 보면 정답은 2번과 같습니다.
다만, Interface에서는 다중상속을 지원하고 있습니다.

해당 글을 참고하시면 도움이 될 것 같습니다.
https://mainia.tistory.com/2139

**Comment by LimHyungang** [comment]
답변 감사드립니다.
