### ISSUE TITLE
깃 허브 연동 방법이 궁금합니다.

### ISSUE THREAD

**Issue by tmdrud7766** [seed-kau/JavaStudy#6]
마크다운 사용법 잘쓰이는거 알고 싶엉

**Comment by Danpatpang** [comment]
깃허브는 버전 제어 및 공동 작업을 위한 오픈소스 플랫폼으로 public 프로젝트의 경우 누구나 접근이 가능합니다.

Issues의 경우, 전체를 대상으로 공개되므로 주제에 맞는 Label을 다는 것과 사적인 표현을 사용하지 않는 것이 좋습니다.

질문에 대해서는 정확하게 어떤 것을 말씀하시는지 잘 모르겠습니다.

질문에 대해서 좀 더 구체적으로 적어주시면 감사하겠습니다.

마크다운의 경우는 [Haroopad](http://pad.haroopress.com/page.html) 에디터를 사용하면 더욱 쉽게 작성할 수 있습니다.
