### ISSUE TITLE
객체 및 메소드에 대한 개념이 궁금합니다.

### ISSUE THREAD

**Issue by heasun0111** [seed-kau/JavaStudy#7]
'이것이 자바다' P.149를 공부하던 중 객체의 개념에 대한 혼란이 왔으며, 더불어 P.129에 
Scanner scanner = new Scanner(System.in); 에서의 Scanner 객체와 nextLine()메소드 호출에 관한 설명도 듣고싶습니다.

**Comment by boribap** [comment]
Scanner 사용시 주의할 점에 대해 알려드리겠습니다. 

 - nextXXX() 메소드 사용시 주의해야 하는것 
     - 참고자료 ) https://allg.tistory.com/17 
 - 사용하고 난 뒤 close() 해줄 것
