### ISSUE TITLE
마크다운 포맷 무시방법

### ISSUE THREAD

**Issue by Twoketchupplz** [seed-kau/JavaStudy#8]
비트 이동 연산자 >> >>>를 작성하려는데 마크다운 포맷이 사용되요
백슬래시도 넣어보고 HTML코드도 써봤는데 계속 똑같은 결과가 나옵니다.
구글에 검색해보면 제가 해본 방법만 뜹니다.

**Comment by Danpatpang** [comment]
마크다운에서 >> 또는 >>>를 사용하고 싶으시면 `>>` 또는 `>>>`를 사용해보세요!

**Comment by Danpatpang** [comment]
```
`>>` 또는 `>>>`입니다.
```
작은따옴표가 아니라 숫자 1옆에 있는 기호임에 주의해주세요.

**Comment by Twoketchupplz** [comment]
그래도 제가 이번에 올린 글을 preview로 봤을때 안되용..

**Comment by Danpatpang** [comment]
html 특수 문자표를 참고해보세요!
http://egloos.zum.com/keep/v/1030642
