### ISSUE TITLE
참조타입과 클래스에 대한 질문입니다.

### ISSUE THREAD

**Issue by aldrn29** [seed-kau/JavaStudy#9]
### 1. 열거타입 (171p)
참조타입 중 열거타입이라는게 데이터 중에 한정된 값만 갖는 경우에 쓰는거라고 하는데, 이런 열거타입은 언제 쓰이나요? 

### 2. 객체와 인스턴스 (191p)
클래스로부터 만들어진 객체를 해당 클래스의 인스턴스라고 하는데, 객체와 인스턴스가 같다고 생각하면 되나요?

### 3. 정적 메소드와 블록 선언시 주의할 점 (240p)
static과 인스턴스간이루어지는 접근이 잘 이해가 가지 않습니다.
클래스가 메모리로 로딩되면 정적 멤버를 사용할 수 있고, 정적 필드와 메소드에서는 인스턴스 필드나 메소드를 사용할 수가 없는데, new해서 객체를 생성해서 참조 변수로 접근한다는게 무슨 뜻이죠?

**Comment by boribap** [comment]
<참고자료>

1. 열거타입 
 http://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

2. 객체와 메소드 
https://alfredjava.wordpress.com/2008/07/08/class-vs-object-vs-instance/
